### ISSUE TITLE
bug: Cannot find module 'sass-embedded'

### ISSUE THREAD

**Issue by rd-stefan-riehmer** [stenciljs/sass#593]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/stenciljs/core/blob/main/CONTRIBUTING.md).
- [x] I agree to follow the [Code of Conduct](https://github.com/stenciljs/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have searched for [existing issues](https://github.com/stenciljs/sass/issues) that already report this problem, without success.

### Stencil Sass Version

3.1.7

### Stencil Version

4.27.1

### Current Behavior

Running `npm start` or tests `npm run test.watch` fails with a `Error: Cannot find module 'sass-embedded'` (see stacktrace below) when upgrading stencil/sass from 3.0.12 to 3.1.7

Happens on latest mac or ubuntu.

### Expected Behavior

There should be no missing "sass-embedded" module.

### Steps to Reproduce

1. Use a stencil js project with the following package.json:

```
  "dependencies": {
    "@stencil/core": "^4.27.1",
  },
  "devDependencies": {
    "@stencil/sass": "^3.1.7",
    "@types/jest": "^27.0.3",
    "jest": "^27.4.5",
    "jest-cli": "^27.4.5",
    "puppeteer": "^24.3.0"
  }
```

2. run `npm i`
3. run `npm start` or `npm run test.watch`
4. Observe error on the command line

### Code Reproduction URL

https://github.com/rd-stefan-riehmer/stencil-sass-error

### Additional Information

Stacktrace

```
  stencil-project % npm start
> rewe-digital-components@0.0.1 start
> stencil build --dev --watch --serve --no-open

[18:46.1]  @stencil/core
[18:46.4]  v4.27.1 🍸

[ ERROR ]  Error: Cannot find module 'sass-embedded' Require stack: -
           /Users/user/dev/stencil-project/node_modules/@stencil/sass/dist/index.js
           -
           /Users/user/dev/stencil-project/stencil.config.ts
           -
           /Users/user/dev/stencil-project/node_modules/@stencil/core/compiler/stencil.js
           -
           /Users/user/dev/stencil-project/node_modules/@stencil/core/sys/node/index.js
           -
           /Users/user/dev/stencil-project/node_modules/@stencil/core/bin/stencil
           at Function._resolveFilename
           (node:internal/modules/cjs/loader:1410:15) at defaultResolveImpl
           (node:internal/modules/cjs/loader:1061:19) at resolveForCJSWithHooks
           (node:internal/modules/cjs/loader:1066:22) at Function._load
           (node:internal/modules/cjs/loader:1215:37) at
           TracingChannel.traceSync (node:diagnostics_channel:322:14) at
           wrapModuleLoad (node:internal/modules/cjs/loader:234:24) at
           Module.require (node:internal/modules/cjs/loader:1496:12) at require
           (node:internal/modules/helpers:135:16) at Object.<anonymous>
           (/Users/user/dev/stencil-project/node_modules/@stencil/sass/dist/index.js:3:20)
           at Module._compile (node:internal/modules/cjs/loader:1740:14)

```
